services:
  mysql:
    image: mysql:8.4
    container_name: mindfit-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mindfit_db
      MYSQL_USER: mindfit_app
      MYSQL_PASSWORD: mindfit_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./infra/mysql/init:/docker-entrypoint-initdb.d
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --slow_query_log=1
      --long_query_time=1
volumes:
  mysql_data:
